-- ============================================
-- Supabase Setup for Palestinian Legal Advisor
-- Hybrid RAG System with pgvector
-- ============================================

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create law_chunks table for storing legal content with embeddings
CREATE TABLE IF NOT EXISTS law_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    metadata JSONB NOT NULL,
    embedding vector(768), -- Gemini text-embedding-004 produces 768-dimensional vectors
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create index for vector similarity search (HNSW for better performance)
CREATE INDEX IF NOT EXISTS law_chunks_embedding_idx 
ON law_chunks 
USING hnsw (embedding vector_cosine_ops);

-- 4. Create index for metadata queries (e.g., filtering by source_url)
CREATE INDEX IF NOT EXISTS law_chunks_metadata_idx 
ON law_chunks 
USING gin (metadata);

-- 5. Create function for semantic search (vector similarity)
CREATE OR REPLACE FUNCTION match_law_chunks(
    query_embedding vector(768),
    match_threshold float DEFAULT 0.7,
    match_count int DEFAULT 5
)
RETURNS TABLE (
    id UUID,
    content TEXT,
    metadata JSONB,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        law_chunks.id,
        law_chunks.content,
        law_chunks.metadata,
        1 - (law_chunks.embedding <=> query_embedding) AS similarity
    FROM law_chunks
    WHERE law_chunks.embedding IS NOT NULL
        AND 1 - (law_chunks.embedding <=> query_embedding) > match_threshold
    ORDER BY law_chunks.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 6. Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_law_chunks_updated_at
    BEFORE UPDATE ON law_chunks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 7. Optional: Create view for easy querying without embeddings (lighter queries)
CREATE OR REPLACE VIEW law_chunks_summary AS
SELECT 
    id,
    content,
    metadata,
    created_at,
    updated_at
FROM law_chunks;

-- 8. Optional: Add RLS (Row Level Security) policies if needed
-- Uncomment if you want to enable RLS for multi-user scenarios
-- ALTER TABLE law_chunks ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "Allow public read access" ON law_chunks
--     FOR SELECT USING (true);

-- CREATE POLICY "Allow authenticated insert" ON law_chunks
--     FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ============================================
-- Sample Query Examples (for testing)
-- ============================================

-- Test 1: Insert a sample chunk (manual test)
-- INSERT INTO law_chunks (content, metadata, embedding)
-- VALUES (
--     'المادة 1: يعاقب بالحبس مدة لا تقل عن سنة...',
--     '{"source_url": "https://example.com", "law_name": "قانون العقوبات", "date_fetched": "2025-11-30"}'::jsonb,
--     NULL -- Embedding will be generated by the app
-- );

-- Test 2: Search for similar chunks (after embeddings are generated)
-- SELECT * FROM match_law_chunks(
--     '[0.1, 0.2, ...]'::vector(768), -- Your query embedding here
--     0.7, -- Similarity threshold
--     5    -- Number of results
-- );

-- Test 3: Check table contents
-- SELECT id, LEFT(content, 50) as content_preview, metadata->>'law_name' as law_name, created_at
-- FROM law_chunks
-- ORDER BY created_at DESC
-- LIMIT 10;
